title:
description:
logo: assets/me.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: G-HG9ECTKN4W

defaults:
  -
    scope:
      path: ""
    values:
      css: "/assets/css/style.css"
